export { startTruthEngine } from './scheduler'
export type { TruthEngineConfig } from './scheduler'
export { detectReinforcement, detectClusterGroups } from './detect'
export type { ReinforcementGroup } from './detect'
export { promoteToTruth } from './promote'
export { decayTruths } from './decay'
export { runClusterAnalysis } from './cluster'
export { runSweep } from './sweep'
export { runDurabilityLifecycle } from './durability'
export type { DurabilityResult } from './durability'
