export { ingest } from './ingest'
export type { IngestResult } from './ingest'
export { startEmbedWorker } from './worker'
export { extractFromRaw } from './extract'
export type { ExtractionResult } from './extract'
export { resolveEntities } from './resolve'
export { isDuplicate } from './dedup'
export type { PipelineConfig, LLMConfig, LLMRole } from './config'
export { defaultPipelineConfig, defaultLLMConfig } from './config'
export { runNoiseAssessment } from './assess'
export { runDedup } from './dedup-sweep'
export type { DedupResult } from './dedup-sweep'
